
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: thanos-receiver
  labels:
    app: thanos-receiver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thanos-receiver
  template:
    metadata:
      labels:
        app: thanos-receiver
    spec:
      containers:
      - name: receive
        image: quay.io/thanos/thanos:v0.24.0
        command:
        - /bin/thanos
        - receive
        - --log.level
        - debug
        - --label
        - "receiver=\"0\""
        - --remote-write.address
        - 0.0.0.0:10908
      - name: query
        image: quay.io/thanos/thanos:v0.24.0
        command:
        - /bin/thanos
        - query
        - --log.level
        - debug
        - --http-address
        - 0.0.0.0:9090
        - --grpc-address
        - 0.0.0.0:11901
        - --endpoint
        - 127.0.0.1:10901
---
apiVersion: v1
kind: Service
metadata:
  name: thanos-receiver
spec:
  type: NodePort
  selector:
    app: thanos-receiver
  ports:
    - port: 80
      targetPort: 10908
      nodePort: 30030
      name: endpoint
    - port: 9090
      targetPort: 9090
      name: admin
